#!/bin/bash
# 开发启动脚本 - 20:30 开始

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║         🚀 开发任务队列 - 自动启动脚本                       ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "⏰ 当前时间: $(date '+%Y-%m-%d %H:%M:%S')"
echo ""
echo "📋 任务队列："
echo "  1️⃣  Auto-Deployment Skill (20:30-23:30)"
echo "  2️⃣  Docker Image (23:30-02:30)"
echo "  3️⃣  Daily Briefing System (02:30-06:30)"
echo ""
echo "🤖 Claude Code 状态："
claude --version
echo ""
echo "⚡ Superpowers 已安装："
ls -1 ~/.agents/skills/ | wc -l | xargs echo "  - 技能数量:"
echo ""
echo "📂 工作目录："
echo "  - OpenClaw Skills: /usr/local/lib/node_modules/openclaw/skills/"
echo "  - Daily Briefing: /root/daily-briefing-system/"
echo "  - TODO Queue: /root/.openclaw/workspace/TODO-Queue.md"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✅ 准备就绪！等待 20:30 开始..."
echo ""
echo "第一个任务命令预览："
echo "  claude \"帮我创建 auto-deploy skill 的目录结构"
echo ""
echo "═══════════════════════════════════════════════════════════════"
